version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - AIR_GO_MOD=true
  #     - AIR_TMP_DIR=/tmp/air
  app:
    image: 19992240/aws-ses-local-go:v0.4.0
    platform: linux/amd64
    ports:
      - "8080:8080"
