FROM golang:1.25.5-alpine AS builder

RUN apk update && apk upgrade && \
    apk --update add git make bash build-base

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY . .

RUN go mod download

CMD ["air"]
