name: Build and Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG=${{ github.ref_name }}
          if [ -z "$TAG" ]; then
            TAG="latest"
          fi
          docker build -t 19992240/aws-ses-local-go:$TAG . 
          docker push 19992240/aws-ses-local-go:$TAG
